### ISSUE TITLE
Not working on iphone

### ISSUE THREAD

**Issue by Dandashii** [rtr-nettest/open-rmbt-website#5] opened 2022-02-09 00:09 UTC
why is the browser test not working on the mac or any iphone?

**Comment by cproof** [comment] 2022-02-09 14:08
The problem is that on latest iOS versions, iOS breaks websocket in upload.
See https://developer.apple.com/forums/thread/685403?login=true

This can be solved by Setting safari =>Advanced=>Experimental Features=>NSURLSession WebSocket to off, but it cannot be automatically detected.

**Comment by Dandashii** [comment] 2022-02-10 01:43
Any work around on this issue without having to change anything in my safari settings or you will have to wait for apple to fix this issue in a patch?

**Comment by cproof** [comment] 2022-02-10 10:30
We did not find a workaround. If you find one, we're happy to apply.
Otherwise we have to wait for Apple to fix it.

**Comment by GreatDandashi** [comment] 2022-03-16 19:03
https://developer.apple.com/forums/thread/685403?page=3

The latest comment says that this problem is fixed in the latest 15.4 update.

Can you confirm?

**Comment by Dandashii** [comment] 2022-03-16 19:05
https://developer.apple.com/forums/thread/685403?page=3

The latest answer says that this problem has been fixed in the 15.4 update.

Can you confirm?

**Comment by cproof** [comment] 2022-03-17 14:24
Thank you!
Yes I can confirm, it seems to work again with iOS 15.4

I'll update the code accordingly

**Closed as completed** 2022-03-17 21:17 UTC
